### PR TITLE
Misc Fixes

### LINKED ISSUE #16: Needs CI integration / Dockerfile-based build workflow

### PR DESCRIPTION
**Pull request by wrboyce**
Fixes #16 #17

### CODE REVIEW

**Comment by lekkas** [comment]
@wrboyce does this connect to any of the open issues? If so can we please connect accordingly to these by using 'Fixes #issueNumber'?

Are we addressing the window-changes and dangling exec shells in a separate PR or is this still a WIP that will include these fixes as well?

**Comment by wrboyce** [comment]
@lekkas I'm still working on those, this is just the fixes for #17 (possible security implications) and addressing #16 so we are producing releases via circle and not manually.

There are appropriate `Connects to` tags in the first and third new commits.

File: resin/main.go [hunk 1]
```diff
@@ -151,6 +150,7 @@ func init() {
 	pflag.CommandLine.StringP("shell", "s", "shell.sh", "Path to shell to execute post-authentication")
 	pflag.CommandLine.StringP("auth-failed-banner", "b", "", "Path to template displayed after failed authentication")
 	pflag.CommandLine.IntP("max-auth-tries", "m", 0, "Maximum number of authentication attempts per connection (default 0; unlimited)")
+	pflag.CommandLine.BoolP("allow-env", "E", false, "Pass environment from client to shell (warning: security implications)")
```
Comment (lekkas) [inline resin/main.go]: Should we show more info to the user on what the default option is?

File: circle.yml [hunk 2]
```diff
@@ -0,0 +1,24 @@
+---
+version: 2
+jobs:
+  build:
+    working_directory: /go/src/github.com/resin-io/sshproxy
+    docker:
+      - image: golang:1.8.3-stretch
```
Comment (lekkas) [inline circle.yml]: I believe the repo should have a Dockerfile that will 
1. define the dependencies of the build process
2. create the build artifacts (and most probably store them in a bind mount directory e.g. `build`). 

That way, if someone wants to rebuild `sshproxy` during development they won't have to 
1. install these manually on their host operating system
2. make sure that their golang version is in sync with this
3. Ideally, during local dev I'd be able to specify which artifact I want to build to avoid building everything (e.g. for the backend 99% of the time it'd be linux_amd64)

To give an example here's what I used to test sshproxy locally

```
# build.sh
SSHPROXY_ARTIFACT=build/linux_amd64/sshproxy

docker run --rm \
	-v $(pwd)/build:/go/src/github.com/resin-io/sshproxy/build \
	-v $(pwd)/sshproxy.go:/go/src/github.com/resin-io/sshproxy/sshproxy.go \
	sshproxy /bin/sh -c "make clean; make $SSHPROXY_ARTIFACT"
```

```
# Dockerfile

RUN apt-get update \
	&& apt-get install -y \
		bzip2 \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /go/src/github.com/resin-io/sshproxy
WORKDIR /go/src/github.com/resin-io/sshproxy

COPY . .

RUN go get ./...
```

File: Makefile [hunk 3]
```diff
@@ -1,25 +1,56 @@
...
+test: test-dep
+	go test -v ./...
+
+release: $(RELEASE_TARBALLS)
+
+upload-dep:
+	go get github.com/aktau/github-release
+
+upload: lint test release upload-dep
+	@test -n "${GITHUB_TOKEN}"
```
Comment (lekkas) [inline Makefile]: Where is this secret managed in circleci?

**Comment by lekkas** [comment]
I see, @wrboyce can you please add 'Fixes ' in the PR description? It's easier to see in the description which Issues (if any) are being addressed by a PR, also `connects to` mostly applies to issues that have a staging/testing/production lifetime (e.g. the backend components)

File: Makefile (hunk 3 above)
Comment (wrboyce) [inline Makefile]: Manually configured via the job settings, similar to how we handle DOCKER_PASSWORD in the `resin-*` components.

File: circle.yml (hunk 2 above)
Comment (wrboyce) [inline circle.yml]: This seems unnecessary to me when you can just run, for example, `docker run --rm -v $PWD:/go/src/github.com/resin-io/sshproxy golang:1.8.3-stretch make -C /go/src/github.com/resin-io/sshproxy test`

File: resin/main.go (hunk 1 above)
Comment (wrboyce) [inline resin/main.go]: Good catch, thanks.

File: Makefile (hunk 3 above)
Comment (lekkas) [inline Makefile]: Got it 👍 By the way it'd still be nice to have signed artifacts (possibly as part of the release notes?)

File: circle.yml (hunk 2 above)
Comment (lekkas) [inline circle.yml]: Even better, it'd be nice then to have a brief note in the README on what the local build workflow is.
